version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
    ports:
      - "3306:3306"
  redis:
    extends:
      file: docker-compose-redis.yml
      service: redis
    ports:
      - "6379:6379"
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      REDIS_URL: redis:6379
    ports:
      - "80:80"
  react:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - python
    links:
      - python
    environment:
      API: http://python:80
    ports:
      - "443:443"
