version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
    ports:
      - "3306:3306"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/html:/var/www/html:ro
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: isu05
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
    ports:
      - "80:80"
  react:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - php
    links:
      - php
    environment:
      API: http://isu04:80
    ports:
      - "444:444"
